# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=0.3.5

maven_group=fr.tathan
archives_name=ExoConfig
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=26.3
# Dependencies
fabric_loader_version=0.19.5
fabric_api_version=0.160.7
neoforge_version=26.3.0.3-beta
modmenu_version=21.0.0-beta.1