# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=0.3.5

maven_group=fr.tathan
archives_name=ExoConfig
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=26.2
# Dependencies
fabric_loader_version=0.19.3
fabric_api_version=0.152.1
neoforge_version=26.2.0.1-beta
modmenu_version=20.0.0-beta.2